config/routes.rb
Rails.application.routes.draw do

  resources :articles 
  resources :images, only: [:create, :destroy, :update, :delete]
  devise_for :users
  get 'contact', to: 'messages#new', as: 'contact'
post 'contact', to: 'messages#create'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
match '/contacts',     to: 'contacts#new',             via: 'get'
resources "contacts", only: [:new, :create]
=begin
 except:[:delete]
 get "/articles" index
 post "/articles" create
 delete "/articles" delete
 get "/articles:id" show
 get "/articles/new" new
 get "/articles/:id/edit" edit
 patch "/articles/:id" update
 put "/articles/:id" update
=end

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :images, :inverse_of => :article, :dependent => :destroy
	accepts_nested_attributes_for :images, allow_destroy: true
	# accepts_nested_attributes_for :images
	before_create :set_visits

	
	geocoded_by :location   # can also be an IP address

	after_validation :geocode, :if => :location_changed?
	after_destroy :rm_img_dir 
	after_create :send_mail
	def update_visits
		
		unless self.visits.nil?
			self.update(visits: self.visits + 1)
		end	
	end
	def rm_img_dir
    	 FileUtils.rm_rf("#{Rails.root}/public/uploads/dir/#{self.id}/")  if self.image
    end
	private

	def set_visits
		self.visits ||=0
	end

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :article
	validates  :article, presence: true
	belongs_to :user
	mount_uploader :dir,  ImageUploader
	attr_accessor :image_width, :image_height
end

app/models/message.rb
class Message

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :content,
    presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :articles
   has_many :images
   before_create :set_permission_lvl
   def set_permission_lvl
		self.permission_lvl ||=0
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end


app/controllers/articles_controller.rb

class ArticlesController < ApplicationController
	before_action  :authenticate_user!, except: [:index, :show]  
	before_action  :set_article, except: [:create, :new, :index]
	# get /articles/
	def index
		@articles = Article.all	
				@art_geojson = Array.new
		@articles.each do | art |
			@art_geojson << {
				 type: 'Feature',
				 geometry: {
					type: 'Point',
					coordinates: [art.longitude, art.latitude]

				 },
				 properties: {
				    id: art.id,
				    img: art.images.first.dir_url(:mini) ,
					price: art.price,
				 	location: art.location,
				 	popupContent: "This is where the Rockies play!"
    				
				 }
			}	
		end	
		respond_to do | format |
			format.html
			format.json { render json: @art_geojson} 
		end	
		
		
		
	end	
	# get /articles/:id	
	def show		
		@article.update_visits
		@image = Image.new
	end
	# GET /articles/new
	def new
		@article = Article.new	
	end
    def edit
    	
    end
	#post /articles/create
	def create
		@article = current_user.articles.new(article_params)
		if @article.save
			if params[:images]
			   params[:images].each { |image|
			   		@article.images.create(dir: image)
			   }
		     end
      		 flash[:notice] = "Your Article has been created."
      		 redirect_to @article
         else 
             flash[:alert] = "Something went wrong."
      		 render :new
  		end
	end	
	def destroy
		@article.destroy

		redirect_to  articles_path
	end
	def update	
		if  @article.update(article_params)
			if params[:images]
			   params[:images].each { |image|
	
					@article.images.create(dir: image)
				}
			end
			flash[:notice] = "Your Article has been created."
			redirect_to @article
		else
			flash[:alert]  = "Something went wrong"
			render :edit
		end
    end

    private
	def set_article
		@article = Article.find(params[:id])
	end
	def article_params
		# params.require(:article).permit(:price,:location, images_attributes: [:id, :image])
		params.require(:article).permit(:price, :location, :sq_mts_t, :sq_mts_c, :baths, :parks, :lvls, :desc, :latitude, :longitude)
	end	
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:new, :show, :edit, :update, :destroy]
  before_action :set_article
  before_action  :authenticate_user!, except: [:index, :show]  
  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new

  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.save
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image.article, notice: 'Imagen Cargada' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image.article, notice: 'Imagen Cargada' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
   respond_to do |format|
      format.html { redirect_to edit_article_path(@image.article),  notice: 'Imagen Eliminada' }
      format.json { head :no_content }
    end
  end

  private
    def  set_article
      #@article = Article.find(params[:article_id])
       @article = @image.article
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through. @article = @image.article
    def image_params
      params.require(:image).permit(:article_id, :dir, :height, :width)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    
    if @message.valid?
      MessageMailer.new_message(@message).deliver
      redirect_to contact_path, notice: "Your messages has been sent."
    else
      flash[:alert] = "An error occurred while delivering this message."
      render :new
    end
  end

private

  def message_params
    params.require(:message).permit(:name, :email, :content)
  end

    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper 
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb

<h2><%= name ||= "Publicar" %></h2>
<div class="row">
<div class="col-md-6 col-xs-12 col-md-12 col-lg-7">
<%= form_for @article, id:"myForm", :html => {:multipart => true} do |f| %>
	<div class="form-group">
		<%=f.text_field :location, placeholder: "Ubicacion",  class:"form-control", id:"address" %>
	</div>
	<div class="form-group">
		<%=f.text_field :price, placeholder: "Precio", class:"form-control"%>
	</div>
	<div class="form-group">
		<%=f.text_field :baths, placeholder: "Baños",  class:"form-control" %>
	</div>	
	<div class="form-group">
		<%=f.text_field :sq_mts_t, placeholder: "Metros Totales",  class:"form-control" %>
	</div>
	<div class="form-group">
		<%=f.text_field :sq_mts_c, placeholder: "Metros Const.",  class:"form-control" %>
	</div>	
	<div class="form-group">
		<%=f.text_field :lvls, placeholder: "Plantas",  class:"form-control" %>
	</div>	
    <div class="form-group">
		<%=f.text_field :parks, placeholder: "Espacios en cochera",  class:"form-control" %>
	</div>	
	<div class="form-group">
		<%=f.text_area( :desc, placeholder: "Descripcion",  class:"form-control", id:"art-desc-txt-area") %>
	</div>
</div>
<div class="col-md-6 col-xs-12 col-md-12 col-lg-5" >
	<div id="map" style="height:600px !important;" ></div>	
</div>	
</div>
<div class="form-group">
    <%= file_field_tag "images[]",  class:"nice-container col-md-12 col-xs-12 col-md-12 col-lg-12",     type: :file, multiple: true %>
</div>
<div class="form-group">
        <div class="nice-container col-md-12 col-xs-12 col-md-12 col-lg-12" id="img-zone">


                        <% @article.images.each.with_index do |image ,  index| %>
                               	 <div class="img-cont">
                               	      <div class="img-delete-link">Borrar</div>
                               
                               	     <%= link_to (image_tag image.dir_url(:mini).to_s) , image , method: :delete ,data: {confirm: "Estas seguro que deseas eliminar esta imagen?"}%>
    
                               </div>
                          <%end%>
  
          
                        <p style="margin:0;font-size:12px;">Click en la imagen para eliminar</p>
         </div> 
</div> 
<div class="row">
    <div class="col-md-4 col-lg-4 col-md-offset-4 col-xs-12 col-lg-offset-4"  >
		<%=f.submit "Guardar", class: "btn btn-block btn-default " , id:"btn_submt"    %>
		<%end%>	
</div> 
</div> 
	

<style>
.img-delete-link{
    float:center;
    position:absolute;
    color: rgba(0, 0, 0, 0.0);
    text-align:center;
}
.img-cont{
    display:inline-block;
    position:relative;
}

.img-cont:hover{
    opacity: 0.5;
    filter: alpha(opacity=50);
}


.img-cont > img {
    position:absolute;
    
}
#mydropzone{
display:inline-block;
float:right;
width: 100%;
height:100%;
    
}
.nice-container{
    padding: 10px;
    background: rgba(144, 144, 144, 0.075);
    border-radius: 4px;
    border: solid 1px rgba(144, 144, 144, 0.5);
    margin:5px;
    
}


#art-desc-txt-area {
  
      height: 230px;
    
}
</style>


<script>	

$(document).ready(function(){
/*  Dropzone.autoDiscover = false;
  var myDropzone = new Dropzone("div#mydropzone",{
    paramName: "images[]", 
    autoProcessQueue: false,
    uploadMultiple: true,
    addRemoveLinks:true,
    parallelUploads:10,
        successmultiple: function(data,response){
      $('#msgBoard').append(response.message).addClass("alert alert-success");
      $('#msgBoard').delay(2000).fadeOut();
      $('#fileslist').val(response.filesList);
      $('#myForm').off('submit').submit();
    }
  });

   */ 
          var options = {
          map: "#map"
        };
        $("#address").geocomplete(options)
          .bind("geocode:result", function(event, result){
            $.log("Result: " + result.formatted_address);
          })
          .bind("geocode:error", function(event, status){
            $.log("ERROR: " + status);
          })
          .bind("geocode:multiple", function(event, results){
            $.log("Multiple: " + results.length + " results found");
          });

        
        
$( "#btn_submt" ).prop( "disabled", true );        
    // img dimentions validaton 800x600
var _URL = window.URL || window.webkitURL;
        type_form = '<%= name  %>';
        if (type_form == 'Modificar')
        	    $( "#btn_submt" ).prop( "disabled", false );
$("#images_").change(function(e) {
    var file, img;
    for (var i = 0; i < this.files.length; i++) {  
    if ((file = this.files[i])) {
        img = new Image(); 

        console.log(type_form);
        img.onload = function() {
            if (this.width >= 800 || this.height >= 600 ){
            	$( "#btn_submt" ).prop( "disabled", false );
            }else{
            	$( "#input_grp" ).append( "<p color=red> Imagen muy pequeña (800 x 600 min)</p>" );
            }
          	
        };
        img.onerror = function() {
            alert( "not a valid file: " + file.type);
        };
        img.src = _URL.createObjectURL(file);
    
    }    
    }
});
        
    

});
  

</script>

<!-- 

      t.float :price
      t.string :location
      t.float :sq_mts_t
      t.float :sq_mts_c
      t.float :baths
      t.integer :lvls
      t.integer :parks
      t.text :desc
      t.text :addr

      t.integer :visits
 -->      

app/views/articles/content.html.erb
  <div class=" container-fluid" >
   <h1><%= @article.location %></h1>
   <div class=" text-right">visits <%=  @article.visits %> <p><%= link_to "Modificar" , edit_article_path(@article) ,  method: :get  %>   <%= link_to 'Atras',  '/articles/' %></p>  </div>
   <p>email <%=  @article.user.email %></p> 
   <div class="row article-info" >
    <div class="col-sm-4 info">
      <p><%= 	 @article.price %></p>
    </div>
    <div class="col-sm-8 pictures">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" >
      <!-- Indicators -->
      <ol class="carousel-indicators ">  
        <% @article.images.each.with_index do |image ,  index| %>
        <%  cl_active_ind = if index == 0 then'class="active"' else ''  end  %>    
        <li data-target="#carousel-example-generic" data-slide-to="<%= index %>" <%= cl_active_ind %></li>
        <%end%>
      </ol>
      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox" >
        <% @article.images.each.with_index do |image ,  index| %>
        <% cl_active = if index == 0 then 'item active' else 'item' end %>
        <div class="<%= cl_active %>">
          <%= image_tag image.dir_url(:large).to_s, class:"img-responsive" %>   
        </div>
        <%end%>
      </div>
      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"  aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="container" style="width:70%; margin-top:50px">
    	<%=  render "form", name: "Modificar"	%>
		<%= link_to 'Atras', :back  %>
</div>   



	

app/views/articles/index.html.erb
<div class=" container-fluid" >
    <div class="row row-first slider_index "  class="col-xs-12 col-sm-12 col-lg-12" >
		    <% @articles.each do |article, index | %>
				<div class="slide"  >
					<%=  link_to (image_tag article.images.first.dir_url(:mini).to_s) , article  %>
					<div class="art_footer">
						<p>
							<%= article.location  %> 	<br/>		
							<% if user_signed_in? %>
								<% if current_user.permission_lvl == 0 %>
	                         		<%=  render "partials/edit_delete_links", avatar: article	%>
								<%end%>	
							<%end%>	
						</p>
					</div>
				</div>
			<%end%>
    </div>
</div>

<div class=" container-fluid" >
    <div  id="map_index" class="row row-second" class="col-xs-12 col-sm-12 col-lg-12">
    </div>
</div>
    
<style>
.art_footer,.art_footer > p {
		line-height: normal ;
		 font-size:14px;
		 margin:5px 0 5px 0;
}

#bx-viewport{
    margin-top: 1% !important;
}
.bx-viewport{
    height:200px
}
.bx-wrapper {
    margin-bottom: 0px !important;
}
.row {
    margin-left: 0px;
    margin-right: 0px;
}

.row-first {
    height:200px;
    position: relative;
}
.row-second {
  border: solid black 1px;
  position: relative;
  height:500px;
}

.panel-group{
    width: 100%;
    position: absolute;
}
 

</style>

<script>
$(document).ready(function(){
    var mymap = L.map('map_index').setView([0, 0], 13);
	L.tileLayer( 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    	attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
    	subdomains: ['a','b','c'],
      	maxZoom: 18
	}).addTo( mymap );
	
	$.ajax({
		dataType: 'text',
		url: '/articles.json',
		success: function (data) {
			var geojson = $.parseJSON(data);
			L.geoJSON(geojson).addTo(mymap);
			mymap.fitBounds(L.geoJSON(geojson).getBounds());
	        var layerGroup = L.geoJSON(geojson, {
      			onEachFeature: function (feature, layer) {
      				if (feature.properties && feature.properties.popupContent) {
      					layer.bindPopup('<strong><h4>' + feature.properties.location  + '</h4><br/><h4>$' + feature.properties.price + '</h4></strong>');
              
                		layer.on('mouseover', function() { layer.openPopup(); });
                		layer.on('mouseout', function() { layer.closePopup(); });
            		}
      				
      			}
    		}).addTo(mymap);

		}			
	});
	
	//slide articles logic
	$('.slider_index').bxSlider({
    	slideWidth: 250,
    	minSlides: 1,
    	maxSlides: 6,
    	moveSlides: 3,
    	slideMargin: 5, 
    	pager: false    
    });

});  
</script>

app/views/articles/new.html.erb
<div class="container"  style="width:70%; margin-top:50px">
		<%=  render "form", name: "Publicar" %>
		<%= link_to 'Atras', :back  %>
</div>   



app/views/articles/show.html.erb
<div class="container" style=" width:98%; height:100%">
    <div class="row">
        <br/>
        <div class="col-sm-12 col-lg-8 col-md-8 col-xs-12 pictures">
             <h4><%= @article.location %> </h4>             
       	</div>	
       	<div class="col-sm-12 col-lg-4 col-md-4 col-xs-12 pictures">
             <h4><strong>Precio: <%= number_to_currency(@article.price , precision: 2) %></strong></h4> 
       	</div>	


    </div>
    <div class="row">
            <div class="col-sm-12 col-lg-8 col-md-8 col-xs-12 pictures">
                <div class="row">
            <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
            <ol class="carousel-indicators">

                          <!-- Wrapper for slides -->

                               <% @article.images.each.with_index do |image ,  index| %>
                               <% if index == 0%>
                               	<% itm='class= "active"'%>
                               <%else%>
                                <% itm=''%>
                               <%end%>
                               <li data-target="#myCarousel" <%=itm%> data-slide-to="<%=index%>">
                               </li>
                               <%end%>
  
                           
            </ol>
            
            
            
            
            
                             <!-- Wrapper for slides -->
                             <div class="carousel-inner" role="listbox">
                               <% @article.images.each.with_index do |image ,  index| %>
                               <% if index == 0%>
                               	<% itm='item active'%>
                               <%else%>
                                <% itm='item'%>
                               <%end%>
                               <div  class="<%=itm%>">
                                 <%= image_tag image.dir_url(:large).to_s, class:"img-responsive" %> 
                               </div>
                               <%end%>
                             </div>
                           
                             <!-- Left and right controls -->
                             <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                               <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                               <span class="sr-only">Previous</span>
                             </a>
                             <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                               <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                               <span class="sr-only">Next</span>
                             </a>
                           </div>
                </div>
                
             </div>
                <div class="row">
                <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12" >
                  <!-- thumb navigation carousel -->
                    <div  id="slider-thumbs"  class="panel panel-default" style="padding:8px;">
                            <!-- thumb navigation carousel items -->
                             <ul class="list-inline" class="panel-body" style="margin:0 0 0 0;" >

                             <!-- Wrapper for thumbnails -->
  
                               <% @article.images.each.with_index do |image ,  index| %>
                               <% if index == 0%>
                               	    <% itm_class='class="selected"'%>
                               <%else%>
                                    <% itm_class=''%>
                               <%end%>
                               <li> 
                                   <a id="carousel-selector-<%=index%>" <%=itm_class%> >
                                       <%= image_tag image.dir_url(:mini).to_s, class:"img-responsive thumb-slide-img" %> 
                                   </a>
                               </li>
                                <%end%>
                            </ul>
                    </div>
                </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-lg-8 col-md-8 col-xs-12 "  style=" width:100%;" >
               <div class="panel panel-default" style="  margin:0 0 0.5em 0;" >
    <div class="panel-heading">
      <h4 class="panel-title">
        <div data-toggle="collapse"  id="head_collapse_desc"  >Descripcion</div>
      </h4>
    </div>
    <div id="collapse_desc" class="info-panel" >
      <div class="panel-body" style="height:350px; overflow: auto;"><%= @article.desc %></div>
    </div>
  </div>      
       	            </div>	
                </div>
   
           </div> 
           <div class="col-sm-12 col-lg-4 col-md-4 col-xs-12 ">
            <div class="panel-group " id="accordion">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">
                        <div  data-toggle="collapse"  id="header-collapse1" ><strong>Datos de la Propiedad</strong></div>
                      </h3>
                    </div>
                    <div id="collapse1" class="info-panel">
                          <div class="panel-body">
                            <table class="table table-condensed" id ="article_info">
    						  <tr class="trst-group-item ">
    						       <td class="table-row-title">Metros Totales:</td><td><%= @article.sq_mts_t %></td> 
    						  </tr>
    						  <tr class="trst-group-item">
    						       <td class="table-row-title">Metros Construidos:</td><td><%= @article.sq_mts_c %></td> 
    						  </tr> 
    					 	 <tr class="trst-group-item">
    					 	      <td class="table-row-title">Baños:</td><td><%= @article.baths %></td>
    					 	 </tr>
    					 	 <tr class="trst-group-item">
    					 	      <td class="table-row-title" >Plantas:</td><td><%= @article.lvls %></td>
    					 	 </tr>
    					 	 <tr class="trst-group-item">
    					 	      <td class="table-row-title" >Espacios en Cochera:</td><td><%= @article.parks %></td>
    					 	 </tr> 
    				       </table>
                          </div>
                    </div>
            </div>

           
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h4 class="panel-title">
                        <div  data-toggle="collapse" data-parent="#accordion" id="header-collapse2" ><strong>Quiero saber mas</strong></div>
                      </h4>
                    </div>
                          <div id="collapse2"  class="info-panel panel-body " >
                             
   
             
                            
                           
                          </div>
                  </div>
                 <div class="panel panel-default">
                    <div class="panel-heading">
                      <h4 class="panel-title">
                        <div data-toggle="collapse" data-parent="#accordion" id="header-collapse3"  ><strong>Como llegar</strong></div>
                      </h4>
                    </div>
                    <div id="collapse3"   class="panel-body   " >
                        <div id="mapdiv"  style="position:relative; width:100%; height:250px;" ></div>
                    </div>
                  </div>
                </div>
            <% if user_signed_in? %>
                <% if current_user.permission_lvl == 0 %>
                    <p style="font-size:16px"><strong><%=  render "partials/edit_delete_links", avatar: @article  %></strong> </p>
                <%end%>
            <%end%>    
    </div>        
    </div>
</div>


<style>

/* Samsung Galaxy S5 Portrait */    
#slider-thumbs{
    margin-bottom:4px;
}


.thumb-slide-img{
    height:100px;
}
.table-row-title{
    font-weight: bold;
}
.panel-body {
    padding: 8px;
}
.trst-group-item{
    font-size:16px;
}
.form-control{
    margin-bottom:8px;
}
.table {
    margin-bottom: 3px;
}

.carousel-inner {
    position: relative;
    width: 100%;
    overflow: hidden;
    margin: auto;
}
.item{
    margin: auto;
    text-align: center;
    overflow: hidden;
}

.selected img {
	opacity:0.5;
}


</style>             
<script>
  $(document).ready(function(){
      /* mobile accordion view*/
     if (screen.width < 420 ){
         console.log(screen.width );
           $(".info-panel").addClass('panel-collapse collapse');  
           $("#collapse_desc").addClass('in');  
           $("#head_collapse_desc").attr("href", "#collapse_desc");
           $("#header-collapse1").attr("href", "#collapse1");
           $("#header-collapse2").attr("href", "#collapse2");

     }
    var mymap = L.map('mapdiv').setView([<%= @article.latitude %> , <%= @article.longitude %>], 18);
    
	L.tileLayer( 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    	attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
    	subdomains: ['a','b','c'],
      	maxZoom: 25
	}).addTo( mymap );
	var marker = L.marker([<%= @article.latitude %> , <%= @article.longitude %>]).addTo(mymap);
	
	/*CarrouseL and thumb slides*/
	$('#myCarousel').carousel({
    interval: 4000
    });

    // handles the carousel thumbnails
    $('[id^=carousel-selector-]').click( function(){
      var id_selector = $(this).attr("id");
      var id = id_selector.substr(id_selector.length -1);
      id = parseInt(id);
      $('#myCarousel').carousel(id);
      $('[id^=carousel-selector-]').removeClass('selected');
      $(this).addClass('selected');
    });
    
    // when the carousel slides, auto update
    $('#myCarousel').on('slid', function (e) {
      var id = $('.item.active').data('slide-number');
      id = parseInt(id);
      $('[id^=carousel-selector-]').removeClass('selected');
      $('[id=carousel-selector-'+id+']').addClass('selected');
    });
  });  
</script>
    

app/views/images/edit.html.erb
<h1>Editing Images</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @image.article %>
</p>

<p>
  <strong>User:</strong>
  <%= @image.user %>
</p>

<p>
  <strong>Res:</strong>
  <%= @image.res %>
</p>

<p>
  <strong>Dir:</strong>
  <%= @image.dir %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/partials/_edit_delete_links.html.erb

<% avatar ||= article %>
<%= link_to "Eliminar" , avatar , method: :delete %> | <%= link_to "Modificar" , edit_article_path(avatar), method: :get %> | Visitas:<%= avatar.visits %> 